version: '2'
services:
  strapi:
    image: strapi/strapi
    environment:
      DATABASE_CLIENT: mongo
      DATABASE_NAME: strapi
      DATABASE_HOST: mongo
      DATABASE_PORT: 27017
      DATABASE_USERNAME: zamo
      DATABASE_PASSWORD: 4^6aist{trbA.tGZCD=K
    volumes:
      - ./app:/srv/app
    ports:
      - '1337:1337'
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: strapi
      MONGO_INITDB_ROOT_USERNAME: zamo
      MONGO_INITDB_ROOT_PASSWORD: 4^6aist{trbA.tGZCD=K
    volumes:
      - ./data:/data/db